name: ${APP_NAME:-backend-template}

services:
  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ${APP_NAME:-backend-template}-api
    restart: unless-stopped
    command:
      [
        'fastapi',
        'run',
        '--port',
        '${PORT:-8000}',
        '--host',
        '${HOST:-0.0.0.0}',
      ]
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      APP_NAME: ${APP_NAME:-backend-template}
      APP_DESCRIPTION: ${APP_DESCRIPTION:-FastAPI Application}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      CELERY_BROKER_URL: redis://redis:${REDIS_PORT:-6379}/0
      CELERY_RESULT_BACKEND: redis://redis:${REDIS_PORT:-6379}/1
      PROMETHEUS_MULTIPROC_DIR: /tmp/prom_metrics
      PROMETHEUS_MULTIPROC_CLEANUP: '1'
    networks:
      - app-network
    volumes:
      - app_logs:/app/logs
      - prom_metrics:/tmp/prom_metrics

  # Celery Worker
  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ${APP_NAME:-backend-template}-celery-worker
    restart: unless-stopped
    command: >
      sh -c "poetry run celery -A app.celery.celery_main:celery_app worker 
             --loglevel=info 
             --queues=default,llm_tasks
             --hostname=worker@%h 
             --max-tasks-per-child=100 
             --time-limit=300 
             --soft-time-limit=240"
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      CELERY_BROKER_URL: redis://redis:${REDIS_PORT:-6379}/0
      CELERY_RESULT_BACKEND: redis://redis:${REDIS_PORT:-6379}/1
      REDIS_URL: redis://redis:${REDIS_PORT:-6379}/0
      PROMETHEUS_MULTIPROC_DIR: /tmp/prom_metrics

    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - app_logs:/app/logs
      - prom_metrics:/tmp/prom_metrics

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME:-backend-template}-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    command: redis-server --appendonly yes --port ${REDIS_PORT:-6379}
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '${REDIS_PORT:-6379}', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # Flower Monitoring
  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ${APP_NAME:-backend-template}-flower
    restart: unless-stopped
    command: >
      sh -c "poetry run celery -A app.celery.celery_main:celery_app flower 
        --port=${FLOWER_PORT:-5555}
        --broker_api=redis://redis:${REDIS_PORT:-6379}/0"
    ports:
      - '${FLOWER_PORT:-5555}:${FLOWER_PORT:-5555}'
    environment:
      CELERY_BROKER_URL: redis://redis:${REDIS_PORT:-6379}/0
      CELERY_RESULT_BACKEND: redis://redis:${REDIS_PORT:-6379}/1
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: ${APP_NAME:-backend-template}-prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROM_RETENTION_TIME:-15d}
      - --web.enable-lifecycle
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - app-network
    ports: ['9090:9090']

  grafana:
    image: grafana/grafana:latest
    container_name: ${APP_NAME:-backend-template}-grafana
    restart: unless-stopped
    ports: ['3030:3000']
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      # Optional provisioning (will be ignored if dirs empty)
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME:-backend-template}-network

volumes:
  app_logs:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  prom_metrics:
    driver: local
