global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: celery_worker_logs
    static_configs:
      - targets: ['localhost:9090'] # placeholder for future pushgateway or exporters
    honor_labels: true
