services:
  # inference-core
  inference-core:
    environment:
      DATABASE_SERVICE: ${DATABASE_SERVICE:-mysql+aiomysql}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-app_db}
      DATABASE_USER: ${DATABASE_USER:-db_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-db_password}

  # Celery Worker
  celery-worker:
    environment:
      DATABASE_SERVICE: ${DATABASE_SERVICE:-mysql+aiomysql}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-app_db}
      DATABASE_USER: ${DATABASE_USER:-db_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-db_password}

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME:-backend-template}-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-your_root_password}
      MYSQL_DATABASE: ${DATABASE_NAME:-app_db}
      MYSQL_USER: ${DATABASE_USER:-db_user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-db_password}
    ports:
      - '${DATABASE_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inference-core-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --character-set-server=${DATABASE_MYSQL_CHARSET:-utf8mb4} --collation-server=${DATABASE_MYSQL_COLLATION:-utf8mb4_general_ci}

volumes:
  mysql_data:
    driver: local
