services:
  # Inference Core Application
  inference-core:
    environment:
      DATABASE_SERVICE: ${DATABASE_SERVICE:-sqlite+aiosqlite}
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./inference_core.db}

    volumes:
      - ./inference_core.db:/inference_core/inference_core.db

  # Celery Worker
  celery-worker:
    environment:
      DATABASE_SERVICE: ${DATABASE_SERVICE:-sqlite+aiosqlite}
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./inference_core.db}

    volumes:
      - ./inference_core.db:/inference_core/inference_core.db

volumes:
  sqlite_data:
    driver: local
