"""Add is_deepagent and subagents to UserAgentInstance

Revision ID: b3dac404c08b
Revises: hard_delete_transition
Create Date: 2026-02-21 20:02:53.872926

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3dac404c08b"
down_revision: Union[str, Sequence[str], None] = "hard_delete_transition"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_agent_subagents",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("subagent_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["user_agent_instances.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subagent_id"], ["user_agent_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parent_id", "subagent_id"),
    )

    op.create_unique_constraint(
        "uq_llm_config_override_scope_key",
        "llm_config_overrides",
        ["scope", "scope_key", "config_key"],
    )
    op.drop_constraint(
        op.f("llm_request_logs_user_id_fkey"), "llm_request_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "llm_request_logs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "user_agent_instances", sa.Column("is_deepagent", sa.Boolean(), nullable=False)
    )
    op.create_unique_constraint(
        "uq_user_agent_instance_user_name",
        "user_agent_instances",
        ["user_id", "instance_name"],
    )
    op.create_unique_constraint(
        "uq_user_llm_preference_user_type_key",
        "user_llm_preferences",
        ["user_id", "preference_type", "preference_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_llm_preference_user_type_key", "user_llm_preferences", type_="unique"
    )
    op.drop_constraint(
        "uq_user_agent_instance_user_name", "user_agent_instances", type_="unique"
    )
    op.drop_column("user_agent_instances", "is_deepagent")
    op.drop_constraint(None, "llm_request_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("llm_request_logs_user_id_fkey"),
        "llm_request_logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "uq_llm_config_override_scope_key", "llm_config_overrides", type_="unique"
    )

    op.drop_table("user_agent_subagents")
    # ### end Alembic commands ###
